In [22]:
import pandas as pd
import string

# No max rows and columns
pd.set_option('display.max_rows', None)
pd.set_option('display.max_columns', None)

olympics_df = pd.read_csv('athlete_events.csv')
noc_regions_df = pd.read_csv('noc_regions.csv')

In [21]:
# Examining main dataset
olympics_df.head(500)

,ID,Name,Sex,Age,Height,Weight,Team,NOC,Games,Year,Season,City,Sport,Event,Medal
0,1,A Dijiang,M,24.0,180.0,80.0,China,CHN,1992 Summer,1992,Summer,Barcelona,Basketball,Basketball Men's Basketball,NaN
1,2,A Lamusi,M,23.0,170.0,60.0,China,CHN,2012 Summer,2012,Summer,London,Judo,Judo Men's Extra-Lightweight,NaN
2,3,Gunnar Nielsen Aaby,M,24.0,NaN,NaN,Denmark,DEN,1920 Summer,1920,Summer,Antwerpen,Football,Football Men's Football,NaN
3,4,Edgar Lindenau Aabye,M,34.0,NaN,NaN,Denmark/Sweden,DEN,1900 Summer,1900,Summer,Paris,Tug-Of-War,Tug-Of-War Men's Tug-Of-War,Gold
4,5,Christine Jacoba Aaftink,F,21.0,185.0,82.0,Netherlands,NED,1988 Winter,1988,Winter,Calgary,Speed Skating,Speed Skating Women's 500 metres,NaN
5,5,Christine Jacoba Aaftink,F,21.0,185.0,82.0,Netherlands,NED,1988 Winter,1988,Winter,Calgary,Speed Skating,"Speed Skating Women's 1,000 metres",NaN
6,5,Christine Jacoba Aaftink,F,25.0,185.0,82.0,Netherlands,NED,1992 Winter,1992,Winter,Albertville,Speed Skating,Speed Skating Women's 500 metres,NaN
7,5,Christine Jacoba Aaftink,F,25.0,185.0,82.0,Netherlands,NED,1992 Winter,1992,Winter,Albertville,Speed Skating,"Speed Skating Women's 1,000 metres",NaN
8,5,Christine Jacoba Aaftink,F,27.0,185.0,82.0,Netherlands,NED,1994 Winter,1994,Winter,Lillehammer,Speed Skating,Speed Skating Women's 500 metres,NaN
9,5,Christine Jacoba Aaftink,F,27.0,185.0,82.0,Netherlands,NED,1994 Winter,1994,Winter,Lillehammer,Speed Skating,"Speed Skating Women's 1,000 metres",NaN
10,6,Per Knut Aaland,M,31.0,188.0,75.0,United States,USA,1992 Winter,1992,Winter,Albertville,Cross Country Skiing,Cross Country Skiing Men's 10 kilometres,NaN
11,6,Per Knut Aaland,M,31.0,188.0,75.0,United States,USA,1992 Winter,1992,Winter,Albertville,Cross Country Skiing,Cross Country Skiing Men's 50 kilometres,NaN
12,6,Per Knut Aaland,M,31.0,188.0,75.0,United States,USA,1992 Winter,1992,Winter,Albertville,Cross Country Skiing,Cross Country Skiing Men's 10/15 kilometres Pu...,NaN
13,6,Per Knut Aaland,M,31.0,188.0,75.0,United States,USA,1992 Winter,1992,Winter,Albertville,Cross Country Skiing,Cross Country Skiing Men's 4 x 10 kilometres R...,NaN
14,6,Per Knut Aaland,M,33.0,188.0,75.0,United States,USA,1994 Winter,1994,Winter,Lillehammer,Cross Country Skiing,Cross Country Skiing Men's 10 kilometres,NaN
15,6,Per Knut Aaland,M,33.0,188.0,75.0,United States,USA,1994 Winter,1994,Winter,Lillehammer,Cross Country Skiing,Cross Country Skiing Men's 30 kilometres,NaN
16,6,Per Knut Aaland,M,33.0,188.0,75.0,United States,USA,1994 Winter,1994,Winter,Lillehammer,Cross Country Skiing,Cross Country Skiing Men's 10/15 kilometres Pu...,NaN
17,6,Per Knut Aaland,M,33.0,188.0,75.0,United States,USA,1994 Winter,1994,Winter,Lillehammer,Cross Country Skiing,Cross Country Skiing Men's 4 x 10 kilometres R...,NaN
18,7,John Aalberg,M,31.0,183.0,72.0,United States,USA,1992 Winter,1992,Winter,Albertville,Cross Country Skiing,Cross Country Skiing Men's 10 kilometres,NaN
19,7,John Aalberg,M,31.0,183.0,72.0,United States,USA,1992 Winter,1992,Winter,Albertville,Cross Country Skiing,Cross Country Skiing Men's 50 kilometres,NaN
20,7,John Aalberg,M,31.0,183.0,72.0,United States,USA,1992 Winter,1992,Winter,Albertville,Cross Country Skiing,Cross Country Skiing Men's 10/15 kilometres Pu...,NaN
21,7,John Aalberg,M,31.0,183.0,72.0,United States,USA,1992 Winter,1992,Winter,Albertville,Cross Country Skiing,Cross Country Skiing Men's 4 x 10 kilometres R...,NaN
22,7,John Aalberg,M,33.0,183.0,72.0,United States,USA,1994 Winter,1994,Winter,Lillehammer,Cross Country Skiing,Cross Country Skiing Men's 10 kilometres,NaN
23,7,John Aalberg,M,33.0,183.0,72.0,United States,USA,1994 Winter,1994,Winter,Lillehammer,Cross Country Skiing,Cross Country Skiing Men's 30 kilometres,NaN
24,7,John Aalberg,M,33.0,183.0,72.0,United States,USA,1994 Winter,1994,Winter,Lillehammer,Cross Country Skiing,Cross Country Skiing Men's 10/15 kilometres Pu...,NaN
25,7,John Aalberg,M,33.0,183.0,72.0,United States,USA,1994 Winter,1994,Winter,Lillehammer,Cross Country Skiing,Cross Country Skiing Men's 4 x 10 kilometres R...,NaN
26,8,"Cornelia ""Cor"" Aalten (-Strannood)",F,18.0,168.0,NaN,Netherlands,NED,1932 Summer,1932,Summer,Los Angeles,Athletics,Athletics Women's 100 metres,NaN
27,8,"Cornelia ""Cor"" Aalten (-Strannood)",F,18.0,168.0,NaN,Netherlands,NED,1932 Summer,1932,Summer,Los Angeles,Athletics,Athletics Women's 4 x 100 metres Relay,NaN
28,9,Antti Sami Aalto,M,26.0,186.0,96.0,Finland,FIN,2002 Winter,2002,Winter,Salt Lake City,Ice Hockey,Ice Hockey Men's Ice Hockey,NaN
29,10,"Einar Ferdinand ""Einari"" Aalto",M,26.0,NaN,NaN,Finland,FIN,1952 Summer,1952,Summer,Helsinki,Swimming,Swimming Men's 400 metres Freestyle,NaN
30,11,Jorma Ilmari Aalto,M,22.0,182.0,76.5,Finland,FIN,1980 Winter,1980,Winter,Lake Placid,Cross Country Skiing,Cross Country Skiing Men's 30 kilometres,NaN
31,12,Jyri Tapani Aalto,M,31.0,172.0,70.0,Finland,FIN,2000 Summer,2000,Summer,Sydney,Badminton,Badminton Men's Singles,NaN
32,13,Minna Maarit Aalto,F,30.0,159.0,55.5,Finland,FIN,1996 Summer,1996,Summer,Atlanta,Sailing,Sailing Women's Windsurfer,NaN
33,13,Minna Maarit Aalto,F,34.0,159.0,55.5,Finland,FIN,2000 Summer,2000,Summer,Sydney,Sailing,Sailing Women's Windsurfer,NaN
34,14,Pirjo Hannele Aalto (Mattila-),F,32.0,171.0,65.0,Finland,FIN,1994 Winter,1994,Winter,Lillehammer,Biathlon,Biathlon Women's 7.5 kilometres Sprint,NaN
35,15,Arvo Ossian Aaltonen,M,22.0,NaN,NaN,Finland,FIN,1912 Summer,1912,Summer,Stockholm,Swimming,Swimming Men's 200 metres Breaststroke,NaN
36,15,Arvo Ossian Aaltonen,M,22.0,NaN,NaN,Finland,FIN,1912 Summer,1912,Summer,Stockholm,Swimming,Swimming Men's 400 metres Breaststroke,NaN
37,15,Arvo Ossian Aaltonen,M,30.0,NaN,NaN,Finland,FIN,1920 Summer,1920,Summer,Antwerpen,Swimming,Swimming Men's 200 metres Breaststroke,Bronze
38,15,Arvo Ossian Aaltonen,M,30.0,NaN,NaN,Finland,FIN,1920 Summer,1920,Summer,Antwerpen,Swimming,Swimming Men's 400 metres Breaststroke,Bronze
39,15,Arvo Ossian Aaltonen,M,34.0,NaN,NaN,Finland,FIN,1924 Summer,1924,Summer,Paris,Swimming,Swimming Men's 200 metres Breaststroke,NaN
40,16,Juhamatti Tapio Aaltonen,M,28.0,184.0,85.0,Finland,FIN,2014 Winter,2014,Winter,Sochi,Ice Hockey,Ice Hockey Men's Ice Hockey,Bronze
41,17,Paavo Johannes Aaltonen,M,28.0,175.0,64.0,Finland,FIN,1948 Summer,1948,Summer,London,Gymnastics,Gymnastics Men's Individual All-Around,Bronze
42,17,Paavo Johannes Aaltonen,M,28.0,175.0,64.0,Finland,FIN,1948 Summer,1948,Summer,London,Gymnastics,Gymnastics Men's Team All-Around,Gold
43,17,Paavo Johannes Aaltonen,M,28.0,175.0,64.0,Finland,FIN,1948 Summer,1948,Summer,London,Gymnastics,Gymnastics Men's Floor Exercise,NaN
44,17,Paavo Johannes Aaltonen,M,28.0,175.0,64.0,Finland,FIN,1948 Summer,1948,Summer,London,Gymnastics,Gymnastics Men's Horse Vault,Gold
45,17,Paavo Johannes Aaltonen,M,28.0,175.0,64.0,Finland,FIN,1948 Summer,1948,Summer,London,Gymnastics,Gymnastics Men's Parallel Bars,NaN
46,17,Paavo Johannes Aaltonen,M,28.0,175.0,64.0,Finland,FIN,1948 Summer,1948,Summer,London,Gymnastics,Gymnastics Men's Horizontal Bar,NaN
47,17,Paavo Johannes Aaltonen,M,28.0,175.0,64.0,Finland,FIN,1948 Summer,1948,Summer,London,Gymnastics,Gymnastics Men's Rings,NaN
48,17,Paavo Johannes Aaltonen,M,28.0,175.0,64.0,Finland,FIN,1948 Summer,1948,Summer,London,Gymnastics,Gymnastics Men's Pommelled Horse,Gold
49,17,Paavo Johannes Aaltonen,M,32.0,175.0,64.0,Finland,FIN,1952 Summer,1952,Summer,Helsinki,Gymnastics,Gymnastics Men's Individual All-Around,NaN
50,17,Paavo Johannes Aaltonen,M,32.0,175.0,64.0,Finland,FIN,1952 Summer,1952,Summer,Helsinki,Gymnastics,Gymnastics Men's Team All-Around,Bronze
51,17,Paavo Johannes Aaltonen,M,32.0,175.0,64.0,Finland,FIN,1952 Summer,1952,Summer,Helsinki,Gymnastics,Gymnastics Men's Floor Exercise,NaN
52,17,Paavo Johannes Aaltonen,M,32.0,175.0,64.0,Finland,FIN,1952 Summer,1952,Summer,Helsinki,Gymnastics,Gymnastics Men's Horse Vault,NaN
53,17,Paavo Johannes Aaltonen,M,32.0,175.0,64.0,Finland,FIN,1952 Summer,1952,Summer,Helsinki,Gymnastics,Gymnastics Men's Parallel Bars,NaN
54,17,Paavo Johannes Aaltonen,M,32.0,175.0,64.0,Finland,FIN,1952 Summer,1952,Summer,Helsinki,Gymnastics,Gymnastics Men's Horizontal Bar,NaN
55,17,Paavo Johannes Aaltonen,M,32.0,175.0,64.0,Finland,FIN,1952 Summer,1952,Summer,Helsinki,Gymnastics,Gymnastics Men's Rings,NaN
56,17,Paavo Johannes Aaltonen,M,32.0,175.0,64.0,Finland,FIN,1952 Summer,1952,Summer,Helsinki,Gymnastics,Gymnastics Men's Pommelled Horse,NaN
57,18,Timo Antero Aaltonen,M,31.0,189.0,130.0,Finland,FIN,2000 Summer,2000,Summer,Sydney,Athletics,Athletics Men's Shot Put,NaN
58,19,Win Valdemar Aaltonen,M,54.0,NaN,NaN,Finland,FIN,1948 Summer,1948,Summer,London,Art Competitions,"Art Competitions Mixed Sculpturing, Unknown Event",NaN
59,20,Kjetil Andr Aamodt,M,20.0,176.0,85.0,Norway,NOR,1992 Winter,1992,Winter,Albertville,Alpine Skiing,Alpine Skiing Men's Downhill,NaN
60,20,Kjetil Andr Aamodt,M,20.0,176.0,85.0,Norway,NOR,1992 Winter,1992,Winter,Albertville,Alpine Skiing,Alpine Skiing Men's Super G,Gold
61,20,Kjetil Andr Aamodt,M,20.0,176.0,85.0,Norway,NOR,1992 Winter,1992,Winter,Albertville,Alpine Skiing,Alpine Skiing Men's Giant Slalom,Bronze
62,20,Kjetil Andr Aamodt,M,20.0,176.0,85.0,Norway,NOR,1992 Winter,1992,Winter,Albertville,Alpine Skiing,Alpine Skiing Men's Slalom,NaN
63,20,Kjetil Andr Aamodt,M,22.0,176.0,85.0,Norway,NOR,1994 Winter,1994,Winter,Lillehammer,Alpine Skiing,Alpine Skiing Men's Downhill,Silver
64,20,Kjetil Andr Aamodt,M,22.0,176.0,85.0,Norway,NOR,1994 Winter,1994,Winter,Lillehammer,Alpine Skiing,Alpine Skiing Men's Super G,Bronze
65,20,Kjetil Andr Aamodt,M,22.0,176.0,85.0,Norway,NOR,1994 Winter,1994,Winter,Lillehammer,Alpine Skiing,Alpine Skiing Men's Giant Slalom,NaN
66,20,Kjetil Andr Aamodt,M,22.0,176.0,85.0,Norway,NOR,1994 Winter,1994,Winter,Lillehammer,Alpine Skiing,Alpine Skiing Men's Slalom,NaN
67,20,Kjetil Andr Aamodt,M,22.0,176.0,85.0,Norway,NOR,1994 Winter,1994,Winter,Lillehammer,Alpine Skiing,Alpine Skiing Men's Combined,Silver
68,20,Kjetil Andr Aamodt,M,26.0,176.0,85.0,Norway,NOR,1998 Winter,1998,Winter,Nagano,Alpine Skiing,Alpine Skiing Men's Downhill,NaN
69,20,Kjetil Andr Aamodt,M,26.0,176.0,85.0,Norway,NOR,1998 Winter,1998,Winter,Nagano,Alpine Skiing,Alpine Skiing Men's Super G,NaN
70,20,Kjetil Andr Aamodt,M,26.0,176.0,85.0,Norway,NOR,1998 Winter,1998,Winter,Nagano,Alpine Skiing,Alpine Skiing Men's Giant Slalom,NaN
71,20,Kjetil Andr Aamodt,M,26.0,176.0,85.0,Norway,NOR,1998 Winter,1998,Winter,Nagano,Alpine Skiing,Alpine Skiing Men's Combined,NaN
72,20,Kjetil Andr Aamodt,M,30.0,176.0,85.0,Norway,NOR,2002 Winter,2002,Winter,Salt Lake City,Alpine Skiing,Alpine Skiing Men's Downhill,NaN
73,20,Kjetil Andr Aamodt,M,30.0,176.0,85.0,Norway,NOR,2002 Winter,2002,Winter,Salt Lake City,Alpine Skiing,Alpine Skiing Men's Super G,Gold
74,20,Kjetil Andr Aamodt,M,30.0,176.0,85.0,Norway,NOR,2002 Winter,2002,Winter,Salt Lake City,Alpine Skiing,Alpine Skiing Men's Giant Slalom,NaN
75,20,Kjetil Andr Aamodt,M,30.0,176.0,85.0,Norway,NOR,2002 Winter,2002,Winter,Salt Lake City,Alpine Skiing,Alpine Skiing Men's Slalom,NaN
76,20,Kjetil Andr Aamodt,M,30.0,176.0,85.0,Norway,NOR,2002 Winter,2002,Winter,Salt Lake City,Alpine Skiing,Alpine Skiing Men's Combined,Gold
77,20,Kjetil Andr Aamodt,M,34.0,176.0,85.0,Norway,NOR,2006 Winter,2006,Winter,Torino,Alpine Skiing,Alpine Skiing Men's Downhill,NaN
78,20,Kjetil Andr Aamodt,M,34.0,176.0,85.0,Norway,NOR,2006 Winter,2006,Winter,Torino,Alpine Skiing,Alpine Skiing Men's Super G,Gold
79,21,Ragnhild Margrethe Aamodt,F,27.0,163.0,NaN,Norway,NOR,2008 Summer,2008,Summer,Beijing,Handball,Handball Women's Handball,Gold
80,22,Andreea Aanei,F,22.0,170.0,125.0,Romania,ROU,2016 Summer,2016,Summer,Rio de Janeiro,Weightlifting,Weightlifting Women's Super-Heavyweight,NaN
81,23,Fritz Aanes,M,22.0,187.0,89.0,Norway,NOR,2000 Summer,2000,Summer,Sydney,Wrestling,"Wrestling Men's Light-Heavyweight, Greco-Roman",NaN
82,23,Fritz Aanes,M,26.0,187.0,89.0,Norway,NOR,2004 Summer,2004,Summer,Athina,Wrestling,"Wrestling Men's Light-Heavyweight, Greco-Roman",NaN
83,24,Nils Egil Aaness,M,24.0,NaN,NaN,Norway,NOR,1960 Winter,1960,Winter,Squaw Valley,Speed Skating,Speed Skating Men's 500 metres,NaN
84,24,Nils Egil Aaness,M,24.0,NaN,NaN,Norway,NOR,1960 Winter,1960,Winter,Squaw Valley,Speed Skating,"Speed Skating Men's 1,500 metres",NaN
85,24,Nils Egil Aaness,M,27.0,NaN,NaN,Norway,NOR,1964 Winter,1964,Winter,Innsbruck,Speed Skating,"Speed Skating Men's 1,500 metres",NaN
86,25,Alf Lied Aanning,M,24.0,NaN,NaN,Norway,NOR,1920 Summer,1920,Summer,Antwerpen,Gymnastics,"Gymnastics Men's Team All-Around, Free System",Silver
87,26,Agnes Erika Aanonsen (-Eyde),F,17.0,169.0,65.0,Norway,NOR,1984 Winter,1984,Winter,Sarajevo,Luge,Luge Women's Singles,NaN
88,27,Johan Aantjes,M,26.0,NaN,NaN,Netherlands,NED,1984 Summer,1984,Summer,Los Angeles,Water Polo,Water Polo Men's Water Polo,NaN
89,28,Jan-Erik Aarberg,M,43.0,170.0,77.0,Norway,NOR,1968 Summer,1968,Summer,Mexico City,Sailing,Sailing Mixed Three Person Keelboat,NaN
90,28,Jan-Erik Aarberg,M,47.0,170.0,77.0,Norway,NOR,1972 Summer,1972,Summer,Munich,Sailing,Sailing Mixed Three Person Keelboat,NaN
91,29,Willemien Aardenburg,F,22.0,NaN,NaN,Netherlands,NED,1988 Summer,1988,Summer,Seoul,Hockey,Hockey Women's Hockey,Bronze
92,30,Pepijn Aardewijn,M,26.0,189.0,72.0,Netherlands,NED,1996 Summer,1996,Summer,Atlanta,Rowing,Rowing Men's Lightweight Double Sculls,Silver
93,30,Pepijn Aardewijn,M,30.0,189.0,72.0,Netherlands,NED,2000 Summer,2000,Summer,Sydney,Rowing,Rowing Men's Lightweight Double Sculls,NaN
94,31,Evald rma (rman-),M,24.0,174.0,70.0,Estonia,EST,1936 Summer,1936,Summer,Berlin,Athletics,Athletics Men's Pole Vault,NaN
95,32,Olav Augunson Aarnes,M,23.0,NaN,NaN,Norway,NOR,1912 Summer,1912,Summer,Stockholm,Athletics,Athletics Men's High Jump,NaN
96,33,Mika Lauri Aarnikka,M,24.0,187.0,76.0,Finland,FIN,1992 Summer,1992,Summer,Barcelona,Sailing,Sailing Men's Two Person Dinghy,NaN
97,33,Mika Lauri Aarnikka,M,28.0,187.0,76.0,Finland,FIN,1996 Summer,1996,Summer,Atlanta,Sailing,Sailing Men's Two Person Dinghy,NaN
98,34,Jamale (Djamel-) Aarrass (Ahrass-),M,30.0,187.0,76.0,France,FRA,2012 Summer,2012,Summer,London,Athletics,"Athletics Men's 1,500 metres",NaN
99,35,Dagfinn Sverre Aarskog,M,24.0,190.0,98.0,Norway,NOR,1998 Winter,1998,Winter,Nagano,Bobsleigh,Bobsleigh Men's Four,NaN
100,36,Stefan Remco Aartsen,M,21.0,194.0,78.0,Netherlands,NED,1996 Summer,1996,Summer,Atlanta,Swimming,Swimming Men's 100 metres Butterfly,NaN
101,36,Stefan Remco Aartsen,M,21.0,194.0,78.0,Netherlands,NED,1996 Summer,1996,Summer,Atlanta,Swimming,Swimming Men's 200 metres Butterfly,NaN
102,36,Stefan Remco Aartsen,M,21.0,194.0,78.0,Netherlands,NED,1996 Summer,1996,Summer,Atlanta,Swimming,Swimming Men's 4 x 100 metres Medley Relay,NaN
103,36,Stefan Remco Aartsen,M,25.0,194.0,78.0,Netherlands,NED,2000 Summer,2000,Summer,Sydney,Swimming,Swimming Men's 100 metres Butterfly,NaN
104,36,Stefan Remco Aartsen,M,25.0,194.0,78.0,Netherlands,NED,2000 Summer,2000,Summer,Sydney,Swimming,Swimming Men's 200 metres Butterfly,NaN
105,37,Ann Kristin Aarnes,F,23.0,182.0,64.0,Norway,NOR,1996 Summer,1996,Summer,Atlanta,Football,Football Women's Football,Bronze
106,38,Karl Jan Aas,M,20.0,NaN,NaN,Norway,NOR,1920 Summer,1920,Summer,Antwerpen,Gymnastics,"Gymnastics Men's Team All-Around, Free System",Silver
107,39,Lars Thorlaksn Aas,M,33.0,NaN,NaN,Norway,NOR,1912 Summer,1912,Summer,Stockholm,Fencing,"Fencing Men's Foil, Individual",NaN
108,39,Lars Thorlaksn Aas,M,33.0,NaN,NaN,Norway,NOR,1912 Summer,1912,Summer,Stockholm,Fencing,"Fencing Men's epee, Individual",NaN
109,39,Lars Thorlaksn Aas,M,33.0,NaN,NaN,Norway,NOR,1912 Summer,1912,Summer,Stockholm,Fencing,"Fencing Men's epee, Team",NaN
110,40,Roald Edgar Aas,M,23.0,NaN,NaN,Norway,NOR,1952 Winter,1952,Winter,Oslo,Speed Skating,"Speed Skating Men's 1,500 metres",Bronze
111,40,Roald Edgar Aas,M,27.0,NaN,NaN,Norway,NOR,1956 Winter,1956,Winter,Cortina d'Ampezzo,Speed Skating,"Speed Skating Men's 1,500 metres",NaN
112,40,Roald Edgar Aas,M,27.0,NaN,NaN,Norway,NOR,1956 Winter,1956,Winter,Cortina d'Ampezzo,Speed Skating,"Speed Skating Men's 5,000 metres",NaN
113,40,Roald Edgar Aas,M,31.0,NaN,NaN,Norway,NOR,1960 Winter,1960,Winter,Squaw Valley,Speed Skating,"Speed Skating Men's 1,500 metres",Gold
114,40,Roald Edgar Aas,M,31.0,NaN,NaN,Norway,NOR,1960 Winter,1960,Winter,Squaw Valley,Speed Skating,"Speed Skating Men's 5,000 metres",NaN
115,40,Roald Edgar Aas,M,31.0,NaN,NaN,Norway,NOR,1960 Winter,1960,Winter,Squaw Valley,Speed Skating,"Speed Skating Men's 10,000 metres",NaN
116,41,Rolf Aas,M,28.0,NaN,NaN,Norway,NOR,1920 Summer,1920,Summer,Antwerpen,Football,Football Men's Football,NaN
117,42,Thomas Valentin Aas,M,25.0,NaN,NaN,Taifun,NOR,1912 Summer,1912,Summer,Stockholm,Sailing,Sailing Mixed 8 metres,Gold
118,43,Morten Gjerdrum Aasen,M,34.0,185.0,75.0,Norway,NOR,1992 Summer,1992,Summer,Barcelona,Equestrianism,"Equestrianism Mixed Jumping, Individual",NaN
119,44,Meelis Aasme,M,25.0,182.0,73.0,Estonia,EST,1998 Winter,1998,Winter,Nagano,Cross Country Skiing,Cross Country Skiing Men's 30 kilometres,NaN
120,44,Meelis Aasme,M,25.0,182.0,73.0,Estonia,EST,1998 Winter,1998,Winter,Nagano,Cross Country Skiing,Cross Country Skiing Men's 50 kilometres,NaN
121,44,Meelis Aasme,M,29.0,182.0,73.0,Estonia,EST,2002 Winter,2002,Winter,Salt Lake City,Cross Country Skiing,Cross Country Skiing Men's 15 kilometres,NaN
122,44,Meelis Aasme,M,29.0,182.0,73.0,Estonia,EST,2002 Winter,2002,Winter,Salt Lake City,Cross Country Skiing,Cross Country Skiing Men's 50 kilometres,NaN
123,44,Meelis Aasme,M,29.0,182.0,73.0,Estonia,EST,2002 Winter,2002,Winter,Salt Lake City,Cross Country Skiing,Cross Country Skiing Men's 4 x 10 kilometres R...,NaN
124,45,Hakon Aasns,M,41.0,NaN,NaN,Norway,NOR,1936 Summer,1936,Summer,Berlin,Shooting,"Shooting Men's Small-Bore Rifle, Prone, 50 metres",NaN
125,46,Hans Aasns,M,33.0,194.0,93.0,Norway,NOR,1936 Summer,1936,Summer,Berlin,Shooting,"Shooting Men's Rapid-Fire Pistol, 25 metres",NaN
126,46,Hans Aasns,M,45.0,194.0,93.0,Norway,NOR,1948 Summer,1948,Summer,London,Shooting,"Shooting Men's Rapid-Fire Pistol, 25 metres",NaN
127,46,Hans Aasns,M,49.0,194.0,93.0,Norway,NOR,1952 Summer,1952,Summer,Helsinki,Shooting,Shooting Men's Trap,NaN
128,46,Hans Aasns,M,53.0,194.0,93.0,Norway,NOR,1956 Summer,1956,Summer,Melbourne,Shooting,Shooting Men's Trap,NaN
129,46,Hans Aasns,M,57.0,194.0,93.0,Norway,NOR,1960 Summer,1960,Summer,Roma,Shooting,Shooting Men's Trap,NaN
130,47,Erling Rudolf Aastad,M,22.0,177.0,74.0,Norway,NOR,1920 Summer,1920,Summer,Antwerpen,Athletics,Athletics Men's 4 x 100 metres Relay,NaN
131,47,Erling Rudolf Aastad,M,22.0,177.0,74.0,Norway,NOR,1920 Summer,1920,Summer,Antwerpen,Athletics,Athletics Men's Long Jump,NaN
132,47,Erling Rudolf Aastad,M,26.0,177.0,74.0,Norway,NOR,1924 Summer,1924,Summer,Paris,Athletics,Athletics Men's Long Jump,NaN
133,47,Erling Rudolf Aastad,M,30.0,177.0,74.0,Norway,NOR,1928 Summer,1928,Summer,Amsterdam,Athletics,Athletics Men's Long Jump,NaN
134,48,Abdelhak Aatakni,M,24.0,NaN,64.0,Morocco,MAR,2012 Summer,2012,Summer,London,Boxing,Boxing Men's Light-Welterweight,NaN
135,49,Moonika Aava,F,24.0,168.0,65.0,Estonia,EST,2004 Summer,2004,Summer,Athina,Athletics,Athletics Women's Javelin Throw,NaN
136,49,Moonika Aava,F,28.0,168.0,65.0,Estonia,EST,2008 Summer,2008,Summer,Beijing,Athletics,Athletics Women's Javelin Throw,NaN
137,50,Arvi Aavik,M,22.0,185.0,106.0,Estonia,EST,1992 Summer,1992,Summer,Barcelona,Wrestling,"Wrestling Men's Heavyweight, Freestyle",NaN
138,50,Arvi Aavik,M,26.0,185.0,106.0,Estonia,EST,1996 Summer,1996,Summer,Atlanta,Wrestling,"Wrestling Men's Heavyweight, Freestyle",NaN
139,51,Nstor Abad Sanjun,M,23.0,167.0,64.0,Spain,ESP,2016 Summer,2016,Summer,Rio de Janeiro,Gymnastics,Gymnastics Men's Individual All-Around,NaN
140,51,Nstor Abad Sanjun,M,23.0,167.0,64.0,Spain,ESP,2016 Summer,2016,Summer,Rio de Janeiro,Gymnastics,Gymnastics Men's Floor Exercise,NaN

In [23]:
# Examining secondary dataset
noc_regions_df

     NOC                            region                        notes
0    AFG                       Afghanistan                          NaN
1    AHO                           Curacao         Netherlands Antilles
2    ALB                           Albania                          NaN
3    ALG                           Algeria                          NaN
4    AND                           Andorra                          NaN
5    ANG                            Angola                          NaN
6    ANT                           Antigua          Antigua and Barbuda
7    ANZ                         Australia                  Australasia
8    ARG                         Argentina                          NaN
9    ARM                           Armenia                          NaN
10   ARU                             Aruba                          NaN
11   ASA                    American Samoa                          NaN
12   AUS                         Australia                          NaN
13   AUT                           Austria                          NaN
14   AZE                        Azerbaijan                          NaN
15   BAH                           Bahamas                          NaN
16   BAN                        Bangladesh                          NaN
17   BAR                          Barbados                          NaN
18   BDI                           Burundi                          NaN
19   BEL                           Belgium                          NaN
20   BEN                             Benin                          NaN
21   BER                           Bermuda                          NaN
22   BHU                            Bhutan                          NaN
23   BIH            Bosnia and Herzegovina                          NaN
24   BIZ                            Belize                          NaN
25   BLR                           Belarus                          NaN
26   BOH                    Czech Republic                      Bohemia
27   BOL                            Boliva                          NaN
28   BOT                          Botswana                          NaN
29   BRA                            Brazil                          NaN
30   BRN                           Bahrain                          NaN
31   BRU                            Brunei                          NaN
32   BUL                          Bulgaria                          NaN
33   BUR                      Burkina Faso                          NaN
34   CAF          Central African Republic                          NaN
35   CAM                          Cambodia                          NaN
36   CAN                            Canada                          NaN
37   CAY                    Cayman Islands                          NaN
38   CGO                 Republic of Congo                          NaN
39   CHA                              Chad                          NaN
40   CHI                             Chile                          NaN
41   CHN                             China                          NaN
42   CIV                       Ivory Coast                          NaN
43   CMR                          Cameroon                          NaN
44   COD  Democratic Republic of the Congo                          NaN
45   COK                      Cook Islands                          NaN
46   COL                          Colombia                          NaN
47   COM                           Comoros                          NaN
48   CPV                        Cape Verde                          NaN
49   CRC                        Costa Rica                          NaN
50   CRO                           Croatia                          NaN
51   CRT                            Greece                        Crete
52   CUB                              Cuba                          NaN
53   CYP                            Cyprus                          NaN
54   CZE                    Czech Republic                          NaN
55   DEN                           Denmark                          NaN
56   DJI                          Djibouti                          NaN
57   DMA                          Dominica                          NaN
58   DOM                Dominican Republic                          NaN
59   ECU                           Ecuador                          NaN
60   EGY                             Egypt                          NaN
61   ERI                           Eritrea                          NaN
62   ESA                       El Salvador                          NaN
63   ESP                             Spain                          NaN
64   EST                           Estonia                          NaN
65   ETH                          Ethiopia                          NaN
66   EUN                            Russia                          NaN
67   FIJ                              Fiji                          NaN
68   FIN                           Finland                          NaN
69   FRA                            France                          NaN
70   FRG                           Germany                          NaN
71   FSM                        Micronesia                          NaN
72   GAB                             Gabon                          NaN
73   GAM                            Gambia                          NaN
74   GBR                                UK                          NaN
75   GBS                     Guinea-Bissau                          NaN
76   GDR                           Germany                          NaN
77   GEO                           Georgia                          NaN
78   GEQ                 Equatorial Guinea                          NaN
79   GER                           Germany                          NaN
80   GHA                             Ghana                          NaN
81   GRE                            Greece                          NaN
82   GRN                           Grenada                          NaN
83   GUA                         Guatemala                          NaN
84   GUI                            Guinea                          NaN
85   GUM                              Guam                          NaN
86   GUY                            Guyana                          NaN
87   HAI                             Haiti                          NaN
88   HKG                             China                    Hong Kong
89   HON                          Honduras                          NaN
90   HUN                           Hungary                          NaN
91   INA                         Indonesia                          NaN
92   IND                             India                          NaN
93   IOA       Individual Olympic Athletes  Individual Olympic Athletes
94   IRI                              Iran                          NaN
95   IRL                           Ireland                          NaN
96   IRQ                              Iraq                          NaN
97   ISL                           Iceland                          NaN
98   ISR                            Israel                          NaN
99   ISV                Virgin Islands, US               Virgin Islands
100  ITA                             Italy                          NaN
101  IVB           Virgin Islands, British                          NaN
102  JAM                           Jamaica                          NaN
103  JOR                            Jordan                          NaN
104  JPN                             Japan                          NaN
105  KAZ                        Kazakhstan                          NaN
106  KEN                             Kenya                          NaN
107  KGZ                        Kyrgyzstan                          NaN
108  KIR                          Kiribati                          NaN
109  KOR                       South Korea                          NaN
110  KOS                            Kosovo                          NaN
111  KSA                      Saudi Arabia                          NaN
112  KUW                            Kuwait                          NaN
113  LAO                              Laos                          NaN
114  LAT                            Latvia                          NaN
115  LBA                             Libya                          NaN
116  LBR                           Liberia                          NaN
117  LCA                       Saint Lucia                          NaN
118  LES                           Lesotho                          NaN
119  LIB                           Lebanon                          NaN
120  LIE                     Liechtenstein                          NaN
121  LTU                         Lithuania                          NaN
122  LUX                        Luxembourg                          NaN
123  MAD                        Madagascar                          NaN
124  MAL                          Malaysia                          NaN
125  MAR                           Morocco                          NaN
126  MAS                          Malaysia                          NaN
127  MAW                            Malawi                          NaN
128  MDA                           Moldova                          NaN
129  MDV                          Maldives                          NaN
130  MEX                            Mexico                          NaN
131  MGL                          Mongolia                          NaN
132  MHL                  Marshall Islands                          NaN
133  MKD                         Macedonia                          NaN
134  MLI                              Mali                          NaN
135  MLT                             Malta                          NaN
136  MNE                        Montenegro                          NaN
137  MON                            Monaco                          NaN
138  MOZ                        Mozambique                          NaN
139  MRI                         Mauritius                          NaN
140  MTN                        Mauritania                          NaN
141  MYA                           Myanmar                          NaN
142  NAM                           Namibia                          NaN
143  NBO                          Malaysia                 North Borneo
144  NCA                         Nicaragua                          NaN
145  NED                       Netherlands                          NaN
146  NEP                             Nepal                          NaN
147  NFL                            Canada                 Newfoundland
148  NGR                           Nigeria                          NaN
149  NIG                             Niger                          NaN
150  NOR                            Norway                          NaN
151  NRU                             Nauru                          NaN
152  NZL                       New Zealand                          NaN
153  OMA                              Oman                          NaN
154  PAK                          Pakistan                          NaN
155  PAN                            Panama                          NaN
156  PAR                          Paraguay                          NaN
157  PER                              Peru                          NaN
158  PHI                       Philippines                          NaN
159  PLE                         Palestine                          NaN
160  PLW                             Palau                          NaN
161  PNG                  Papua New Guinea                          NaN
162  POL                            Poland                          NaN
163  POR                          Portugal                          NaN
164  PRK                       North Korea                          NaN
165  PUR                       Puerto Rico                          NaN
166  QAT                             Qatar                          NaN
167  RHO                          Zimbabwe                          NaN
168  ROT                               NaN         Refugee Olympic Team
169  ROU                           Romania                          NaN
170  RSA                      South Africa                          NaN
171  RUS                            Russia                          NaN
172  RWA                            Rwanda                          NaN
173  SAA                           Germany                          NaN
174  SAM                             Samoa                          NaN
175  SCG                            Serbia        Serbia and Montenegro
176  SEN                           Senegal                          NaN
177  SEY                        Seychelles                          NaN
178  SIN                         Singapore                          NaN
179  SKN                       Saint Kitts     Turks and Caicos Islands
180  SLE                      Sierra Leone                          NaN
181  SLO                          Slovenia                          NaN
182  SMR                        San Marino                          NaN
183  SOL                   Solomon Islands                          NaN
184  SOM                           Somalia                          NaN
185  SRB                            Serbia                          NaN
186  SRI                         Sri Lanka                          NaN
187  SSD                       South Sudan                          NaN
188  STP             Sao Tome and Principe                          NaN
189  SUD                             Sudan                          NaN
190  SUI                       Switzerland                          NaN
191  SUR                          Suriname                          NaN
192  SVK                          Slovakia                          NaN
193  SWE                            Sweden                          NaN
194  SWZ                         Swaziland                          NaN
195  SYR                             Syria                          NaN
196  TAN                          Tanzania                          NaN
197  TCH                    Czech Republic                          NaN
198  TGA                             Tonga                          NaN
199  THA                          Thailand                          NaN
200  TJK                        Tajikistan                          NaN
201  TKM                      Turkmenistan                          NaN
202  TLS                       Timor-Leste                          NaN
203  TOG                              Togo                          NaN
204  TPE                            Taiwan                          NaN
205  TTO                          Trinidad          Trinidad and Tobago
206  TUN                           Tunisia                          NaN
207  TUR                            Turkey                          NaN
208  TUV                               NaN                       Tuvalu
209  UAE              United Arab Emirates                          NaN
210  UAR                             Syria         United Arab Republic
211  UGA                            Uganda                          NaN
212  UKR                           Ukraine                          NaN
213  UNK                               NaN                      Unknown
214  URS                            Russia                          NaN
215  URU                           Uruguay                          NaN
216  USA                               USA                          NaN
217  UZB                        Uzbekistan                          NaN
218  VAN                           Vanuatu                          NaN
219  VEN                         Venezuela                          NaN
220  VIE                           Vietnam                          NaN
221  VIN                     Saint Vincent                          NaN
222  VNM                           Vietnam                          NaN
223  WIF                          Trinidad       West Indies Federation
224  YAR                             Yemen                  North Yemen
225  YEM                             Yemen                          NaN
226  YMD                             Yemen                  South Yemen
227  YUG                            Serbia                   Yugoslavia
228  ZAM                            Zambia                          NaN
229  ZIM                          Zimbabwe                          NaN

In [33]:
print(f"Rows: {olympics_df.shape[0]} Columns: {olympics_df.shape[1]}\n")
print(olympics_df.info())

Rows: 271116 Columns: 15

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 271116 entries, 0 to 271115
Data columns (total 15 columns):
 #   Column  Non-Null Count   Dtype
---  ------  --------------   -----
 0   ID      271116 non-null  int64
 1   Name    271116 non-null  object
 2   Sex     271116 non-null  object
 3   Age     261642 non-null  float64
 4   Height  210945 non-null  float64
 5   Weight  208241 non-null  float64
 6   Team    271116 non-null  object
 7   NOC     271116 non-null  object
 8   Games   271116 non-null  object
 9   Year    271116 non-null  int64
 10  Season  271116 non-null  object
 11  City    271116 non-null  object
 12  Sport   271116 non-null  object
 13  Event   271116 non-null  object
 14  Medal   39783 non-null   object
dtypes: float64(3), int64(2), object(10)
memory usage: 31.0+ MB
None

**Observations:**

- Some heights and weights are NaN
- If an athlete didn't win a medal (gold, silver, or bronze) then they have NaN
- Multiple entries for each event an athlete competes in (so one athlete can have many entries)
- Does not include Olympics more recent than 2016
- Types of columns that are strings are objects (such as Name, Team, City, Medal, etc.)